# Automatically launches GUT tests on push and PR on the main

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker test
        # Using main to get latest fix for GLIBC_2.28 for Godot 4.2
        uses: ceceppa/godot-gut-ci@main
        with:
          godot_version: 4.2
          gut_params: -gdir=res://Tests/

